name: Build 2.12

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - uses: actions/setup-java@v1
      with:
        java-version: 8 
        architecture: x64
    - name: Build and Test
      run: |
        echo "Setting up Python dependencies"
        pip install -r ./requirements.txt
        jep_site_packages_path=`pip show jep | grep "^Location:" | cut -d ':' -f 2 | cut -d ' ' -f 2`
        jep_path=${jep_site_packages_path}/jep
        jep_lib_path=`realpath ${jep_site_packages_path}/../../`
        export LD_LIBRARY_PATH=${jep_path}:${jep_site_packages_path}:${jep_lib_path}:${LD_LIBRARY_PATH}
        export LD_PRELOAD=${jep_lib_path}/libpython3.so

        pushd $GITHUB_WORKSPACE
          echo "Testing with Spark 3.3.4"
          SPARK_VERSION=3.3.4 sbt 'set scalaVersion := "2.12.12"' test

          echo "Testing with Spark 3.5.7 (default)"
          sbt 'set scalaVersion := "2.12.12"' test
        popd
